wolph/python-progressbar

progressbar/bar.py
NEVER NEVER NEVER use an `except` without a type without reraising it.
=> Added correct exception type to ProgressBar.__call__

progressbar/bar.py, progressbar/widgets.py
Before, with the default widgets:
```
$ python3 progress.py 
100% (60 of 60) |########| Elapsed Time: 0:00:06.027589 Time: 0.9040819999999999
```
After:
```
$ python3 progress.py 
100% (60 of 60) |#############################| Elapsed Time: 0:00:06 Time: 6.03
```
Specific changes:
- Hide the microseconds in the `Timer` class. They're either updating too fast to read, or they're out of date by the time you read them anyway. This required some rearranging to make Timer inherit from FormatLabel.
- Fix AdaptiveETA's display of the total elapsed time after progress is finished (see the 'before' example, it says ~0.9 when it should say ~6.0).
- Limit ETA and AdaptiveETA's display of the total elapsed time to 2 decimal places. This was fairly arbitrary, but showing the full floating point …
=> Timing format improvements

progressbar/__init__.py, progressbar/bar.py, progressbar/base.py, progressbar/six.py, progressbar/widgets.py, tests/datatransferbar.py, tests/iterators.py, tests/unknownlength.py
A few fixes for using `UnknownLength` to have a progress indicator with an unspecified maximum:
* Instantiating `ProgressBar(max_value=UnknownLength)` failed entirely on Python 3, because the UnknownLength class wasn't seen as False-y. Fixed the metaclass definition of UnknownLength.
* When the maximum value is unknown, the default widgets used must not rely on max_value, so e.g. `Percentage()` won't work. I've picked AnimatedMarker, Counter and Timer.
* `max_value` can be passed to the start method, so I delayed constructing the default widgets until start() is called. This makes these equivalent:
```python
ProgressBar(max_value=n).start()
ProgressBar().start(max_value=n)
```
And a couple of extra changes:
* I added a `DataTransferBar` subclass of `ProgressBar`, which has sensible …
=> Fixes for UnknownLength handling

progressbar/widgets.py
I've got following error on python 3.5 (windows x64), and made small workaround.
```
File "C:\env\Python35\lib\site-packages\progressbar\bar.py", line 442, in update
super(ProgressBar, self).update(value=value)
File "C:\env\Python35\lib\site-packages\progressbar\bar.py", line 100, in update
super(StdRedirectMixin, self).update(value=value)
File "C:\env\Python35\lib\site-packages\progressbar\bar.py", line 41, in update
self.fd.write('\r' + self._format_line())
File "C:\env\Python35\lib\site-packages\progressbar\bar.py", line 401, in _format_line
widgets = ''.join(self._format_widgets())
File "C:\env\Python35\lib\site-packages\progressbar\bar.py", line 381, in _format_widgets
widget_output = widget(self, data)
File "C:\env\Python35\lib\site-packages\progressbar\widgets.py", line 300, in …
```
=> Fix python 3 unorderable types error in FileTransferSpeed

progressbar/utils.py
* change docstring to reflect reality
* shutil.get_terminal_size() - dimensions order was correct, only names were misleading
* os.environ.get('COLUMNS/LINES') - dimensions order was incorrect
* blessings - _height_and_width is private method, not property; replace with property access and fix order
* _get_terminal_size_* - fix dimensions order
* 80, 24 - correct default terminal height (shutil.get_terminal_size also returns it as fallback)
=> Multiple fixes in utils.get_terminal_size()

progressbar/widgets.py
Often I see a ETA like this:
`99% (2811 of 2822) |############## | Elapsed Time: 0:00:35 ETA:  -1 day, 23:59:58`
=> Fix negative ETA

setup.cfg
Though it seems to be fixed now on PyPi, one of the previous wheels was not built as universal (was py2 only). To prevent this from happening in the future, adding `universal` under `[bdist_wheel]` makes `python setup.py bdist_wheel` always build a universal wheel.
=> Make bdist_wheel universal

progressbar/bar.py
This is to allow nested progressbar to handle window resize properly.
Consider the following case,
```
bar1 = progressbar.ProgressBar(max_value=1000).start()
for i in range(1000):
bar1.update(i)
if i % 100 == 0:
bar2 = progressbar.ProgressBar(max_value=100).start()
for j in range(100):
bar2.update(j)
```
without the fix, bar1 will not be able to resize.
=> restore, rather than overwrite, sigwinch signal

examples.py, progressbar/widgets.py, tests/timed.py
When using progressbar on generators, for example:
```python
def gen():
for x in range(200):
yield None
widgets = [progressbar.Counter(), ' ',  progressbar.Percentage(), ' ',
progressbar.SimpleProgress(), ' ']
bar = progressbar.ProgressBar(widgets=widgets)
for i in bar(gen()):
sleep(0.02)
```
progressbar raises criptic formatting-related exceptions, mostly due to the missing max_value and related non computable variable. 
This patch allows progressbar to safely display "N/A" (or anything else, of course it's open for discussion) instead of percentages and ETAs instead of crashing.
=> Allow some widgets to be used with generators

progressbar/utils.py
Currently, the number of columns and rows used by `progressbar2` in Jupyter notebooks is inherited from the shell from which it was run... which leads to some pretty weird behaviour. Instead, I think we should check for Jupyter notebooks first.
Is there ever a case where this doesn't make sense?
@WoLpH
=> Check for Jupyter Notebook before allocating other terminal sizes.

progressbar/utils.py, tests/test_stream.py
Hi @WoLpH,
Looks like you've got a couple of off-by-one errors here, which leads to the stdout/stderr not being restored appropriately. Causing some bugs downstream :).
=> Fix unwrapping stdout/stderr

progressbar/bar.py
Sometimes, like if the progressbar is used as part of logging, it is useful to be able to overwrite the progress bar simply using `\r`, which is made more difficult by this dangling newline. This PR makes that optional (the keyword argument name can be changed... chosen here to match the `print` function).
=> Make printing a newline on finish optional

progressbar/utils.py
Upstream IPython discourages using `get_ipython` from global namespace, and it seems not to be present in newer notebook versions, leading to poor choice of terminal width.
=> Use get_ipython imported from IPython rather than global namespace

progressbar/widgets.py
It would be nicer to rename `total_seconds_elapsed` to elapsed as in
`ETA` but this solution does not break the interface. Also this solution
follows `ETA` and uses values from data if and only if `value` or
`total_seconds_elapsed` is Null.
=> fixes #122

progressbar/utils.py
Hello. Just noticed this `print()` statement here that probably should be a logger call.
=> Convert extraneous print statement to `logger.debug` call.

tests/test_monitor_progress.py
I was not able to test this with 'tox'  I am not familiar with it.  I'll look into it a bit more, but wanted to get this out there for you to look at.
From Issue #154
> unfortunately this type of bug is hard to test for
I think I've setup two tests that can detect the two types of failures in #154,  I wasn't sure sure what to name the tests but I went with test_monitor_progress.py.  test_simple_example and test_rapid_updates
Hopefully this test is acceptable and can be the framework for more thorough tests in the future.  I think I could write a test for issue #155 even.
To validate my test I did the following
I went through and ran the tests for every tagged version in git.  I first tested if the simple script
``` python
import time
import progressbar
bar = progressbar.ProgressBar()
for …
```
=> Add New Test Which Monitors Output

setup.py, tox.ini
If you only want to use `python setup.py build`, this change makes its dependencies correct.
=> Fix setup.py build dependency

progressbar/utils.py
`StreamWrapper.__init__` calls `self.wrap_stdout/err` which uses `logger`, so the global `logger` variable has to be initialized first.
=> Fix WRAP_STDOUT/ERR

progressbar/bar.py
The user has the option to finish the progressbar without setting the state to 100 percent.
This is sometimes helpful for example when you abort your program, but want to know, how far the progress was.
In my case I draw the current usage of the disk with the progressbar.
=> Allow to finish the progressbar dirty

progressbar/__init__.py, progressbar/bar.py, progressbar/utils.py
This patch will ignore ANSI escape codes when calculating the length of the string.
E.g. the string `\033[96mtest\033[0m` has the length `4` instead of `13`. (`\033` is one character.)
=> Consider ANSI escape codes when calculating the text length

progressbar/utils.py
I think this is more resilient than before.
=> Only remove the ANSI escape codes if len_color gets a string as parameter

examples.py, progressbar/__init__.py, progressbar/bar.py, progressbar/utils.py, progressbar/widgets.py, tests/test_custom_widgets.py, tests/test_failure.py
I often want to display a task name before the progress bar.
While this is possible with DynamicMessage and FormatCustomText, I find that it could be better: 
- I want placeholders to be very easy to setup: Just adding `prefix="{placeholders.myPlaceholder}` instead of seting up custom widgets
- I want them to be easy to update, with `bar.update(myPlaceholder=newValue)`
This adds a new `placeholders={"name": "value"}` parameter to the constructor, which must be used to set initial values to all placeholders. 
Everything is stored into the `placeholders` object: 
We can use a `format="{placeholders.myPlaceholder}"` to display them in a FormatLabel.
Another option would be to make the placeholders available at the top level: `format="{myPlaceholder}"`, however I wanted to avoid name …
=> Easier to use user-defined placeholders

examples.py, progressbar/bar.py, progressbar/utils.py, progressbar/widgets.py, pytest.ini, tests/conftest.py, tests/test_custom_widgets.py, tests/test_monitor_progress.py, tests/test_progressbar.py, tests/test_utils.py
The problem:
------------
The progressbars are beautiful on an interactive shell.
However, when running from a CI or something else that produces a log file, it is just a big messy blob of garbage.
Depending on how `\r` is handled by the viewer, we get either a very long and noisy line of text, or 3 empty lines between each update.
We also get too many updates for a log file -- This is addressed on #206.
---
The solution:
-------------
It now detects if it is running on an interactive shell via `fd.isatty()`.
This detection is not completely reliable, so it can also be specified via argument or environment variables
If it is not an interactive terminal:
- It writes one update per line, instead of overwrite the existing line
- It removes ANSI color escapes.
=> Do not send garbage when the output is not a terminal

examples.py, progressbar/bar.py
On #175 and #204, we discussed about rate-limiting updates to avoid flooding log files.
This PR addressed this by adding `min_pool_interval` parameter, which works exactly like the existing `_MINIMUM_UPDATE_INTERVAL`
(It can also be specified by the environment variable `PROGRESSBAR_MINIMUM_UPDATE_INTERVAL`)
I also refactored all the checks into `_needs_update`, and added a bypass in case a dynamic_message changes.
=> Prevent updating too often

examples.py, progressbar/bar.py, progressbar/utils.py
StdRedirectMixin makes the bar erase itself before writing the new update.
This works fine and is invisible most of the time.
But only most of the time -- If the refreshes are very fast, flickering becomes visible
This PR first checks if there is something buffered to be written in stdout/stderr, and doesn't erase the current line otherwise
=> Avoid flickering

progressbar/utils.py
Using distutils emits a DeprecationWarning with python 3.10 at
runtime. (And the module is slated for removal in python 3.12.)
The list of accepted strings is taken from
https://docs.python.org/3/distutils/apiref.html#distutils.util.strtobool
=> Stop using deprecated distutils.util

pyproject.toml
Fix the exclusion rules to use wildcards, as that is necessary to recursive exclude a directory.  Otherwise, `docs/_theme` is still included.
=> Fixed excluding docs from install

progressbar/widgets.py
In Windows CPython, format_time() can throw "OSError: [Errno 22] Invalid argument" when passed a very large date. Ignore this in ETA.__call__() with contextlib.suppress().  Fixes #297.
=> Handle OSError exception from format_time() in ETA.__call__()
